{"name": "#正确的账号、错误的密码、正确的验证码", "status": "passed", "description": "错误的账号", "attachments": [{"name": "log", "source": "a1feea10-134c-4bd4-b37f-80a9dbcae8fd-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "b4f5862b-388a-4e0e-9c3d-efe186c085d9-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "48caf78c-d4d4-40d7-b8e7-b24e09696cd4-attachment.txt", "type": "text/plain"}], "start": 1618313555244, "stop": 1618313559697, "uuid": "a6775d26-6f8c-4100-a335-aba945a34011", "historyId": "883a541f97fe6c8c9ddfd4c2f0cae9b6", "testCaseId": "60c800e0ac0825f582650298f219264b", "fullName": "script.test_login.Test_login#test_error_account", "labels": [{"name": "story", "value": "用例2：正确的账号、错误的密码、正确的验证码"}, {"name": "feature", "value": "登录功能"}, {"name": "parentSuite", "value": "script"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_login"}, {"name": "host", "value": "DESKTOP-BN9QCCJ"}, {"name": "thread", "value": "9596-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "script.test_login"}], "links": [{"type": "test_case", "url": "https://mail.qq.com/", "name": "qq邮箱"}]}