{"name": "#正确的账号、错误的密码、正确的验证码", "status": "passed", "description": "错误的账号", "attachments": [{"name": "log", "source": "3afb61f4-8a8c-475a-ac7c-d5f3e3edd68b-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "fd314a2e-8b30-4a69-a3cc-08740619cc83-attachment.txt", "type": "text/plain"}], "start": 1618312770609, "stop": 1618312774999, "uuid": "90de9c93-4387-434e-8480-39b85930d59b", "historyId": "883a541f97fe6c8c9ddfd4c2f0cae9b6", "testCaseId": "60c800e0ac0825f582650298f219264b", "fullName": "script.test_login.Test_login#test_error_account", "labels": [{"name": "feature", "value": "登录功能"}, {"name": "story", "value": "用例2：正确的账号、错误的密码、正确的验证码"}, {"name": "parentSuite", "value": "script"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_login"}, {"name": "host", "value": "DESKTOP-BN9QCCJ"}, {"name": "thread", "value": "14404-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "script.test_login"}], "links": [{"type": "test_case", "url": "https://mail.qq.com/", "name": "qq邮箱"}]}